{{- if .Values.caCertBundle.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caCertBundle.secretName }}
type: Opaque
data:
  {{ .Values.caCertBundle.secretKey }}: {{ .Values.caCertBundle.certBase64 }}  # Inject the base64 cert
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: TrustBundle
metadata:
  name: {{ include "artemis.fullname" . }}-ca-bundle
spec:
  sources:
    - secret:
        name: {{ .Values.caCertBundle.secretName }}  # Secret that contains the CA cert
        key: {{ .Values.caCertBundle.secretKey }}    # The key containing the CA cert


{{- end }}