apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-common
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-common.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">

        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $fullname := include "artemis.fullname" . -}}
        {{- $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $releaseNamespace := .Release.Namespace -}}

        <connectors>
          {{ range $i,$t := until (int .Values.replicas) }}
          {{ range tuple "master" "slave" }}
          <connector name="{{ $fullname }}-{{ . }}-{{ $i }}">tcp://{{ $fullname }}-{{ . }}-{{ $i }}.{{ $releaseName }}-{{ . }}.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{ end }}
          {{end}}
        </connectors>

        <!-- Acceptors -->
        <acceptors>

            <!-- useEpoll means: it will use Netty epoll if you are on a system (Linux) that supports it -->
            <!-- amqpCredits: The number of credits sent to AMQP producers -->
            <!-- amqpLowCredits: The server will send the # credits specified at amqpCredits at this low mark -->
            <!-- amqpDuplicateDetection: If you are not using duplicate detection, set this to false
                                         as duplicate detection requires applicationProperties to be parsed on the server. -->
            <!-- amqpMinLargeMessageSize: Determines how many bytes are considered large, so we start using files to hold their data.
                                          default: 102400, -1 would mean to disable large message control -->

            <!-- Note: If an acceptor needs to be compatible with HornetQ and/or Artemis 1.x clients add
                       "anycastPrefix=jms.queue.;multicastPrefix=jms.topic." to the acceptor url.
                       See https://issues.apache.org/jira/browse/ARTEMIS-1644 for more information. -->


            <!-- Acceptor for every supported protocol -->
            <acceptor name="artemis">tcp://message-broker-2:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;amqpMinLargeMessageSize=102400;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpDuplicateDetection=true;supportAdvisory=false;suppressInternalManagementObjects=false</acceptor>

            <!-- AMQP Acceptor.  Listens on default AMQP port for AMQP traffic.-->
            <acceptor name="amqp">tcp://message-broker-2:5672?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=AMQP;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpMinLargeMessageSize=102400;amqpDuplicateDetection=true</acceptor>

            <!-- STOMP Acceptor. -->
            <acceptor name="stomp">tcp://message-broker-2:61613?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=STOMP;useEpoll=true</acceptor>

            <!-- HornetQ Compatibility Acceptor.  Enables HornetQ Core and STOMP for legacy HornetQ clients. -->
            <acceptor name="hornetq">tcp://message-broker-2:5445?anycastPrefix=jms.queue.;multicastPrefix=jms.topic.;protocols=HORNETQ,STOMP;useEpoll=true</acceptor>

            <!-- MQTT Acceptor -->
            <acceptor name="mqtt">tcp://message-broker-2:1883?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=MQTT;useEpoll=true</acceptor>

        </acceptors>


        <cluster-connections>
          <cluster-connection name="{{ $releaseName }}">
            <connector-ref>netty-connector</connector-ref>
            <retry-interval>500</retry-interval>
            <retry-interval-multiplier>1.1</retry-interval-multiplier>
            <max-retry-interval>5000</max-retry-interval>
            <initial-connect-attempts>-1</initial-connect-attempts>
            <reconnect-attempts>-1</reconnect-attempts>

            <message-load-balancing>ON_DEMAND</message-load-balancing>
            <max-hops>1</max-hops>

            <static-connectors>
            {{ range $i,$t := until (int .Values.replicas) }}
              {{ range tuple "master" "slave" }}
                <connector-ref>{{ $fullname }}-{{ . }}-{{ $i }}</connector-ref>
              {{ end }}
            {{ end }}
            </static-connectors>

          </cluster-connection>
        </cluster-connections>
        <security-settings>
            <!--security for example queue-->
            <security-setting match="exampleQueue">
                <permission roles="guest" type="createDurableQueue"/>
                <permission roles="guest" type="deleteDurableQueue"/>
                <permission roles="guest" type="createNonDurableQueue"/>
                <permission roles="guest" type="deleteNonDurableQueue"/>
                <permission roles="guest" type="consume"/>
                <permission roles="guest" type="send"/>
            </security-setting>
            <security-setting match="#">
                <permission roles="amq" type="createNonDurableQueue"/>
                <permission roles="amq" type="deleteNonDurableQueue"/>
                <permission roles="amq" type="createDurableQueue"/>
                <permission roles="amq" type="deleteDurableQueue"/>
                <permission roles="amq" type="createAddress"/>
                <permission roles="amq" type="deleteAddress"/>
                <permission roles="amq" type="consume"/>
                <permission roles="amq" type="browse"/>
                <permission roles="amq" type="send"/>
                <!-- we need this otherwise ./artemis data imp wouldn't work -->
                <permission roles="amq" type="manage"/>
            </security-setting>
        </security-settings>

        <addresses>
            <address name="exampleQueue">
                <anycast>
                    <queue name="exampleQueue"/>
                </anycast>
            </address>
        </addresses>

        <xi:include href="etc/broker-ha.xml"/>

        <broker-plugins>
            <broker-plugin class-name="org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin">
                <property key="LOG_ALL_EVENTS" value="true"/>
                <property key="LOG_CONNECTION_EVENTS" value="true"/>
                <property key="LOG_SESSION_EVENTS" value="true"/>
                <property key="LOG_CONSUMER_EVENTS" value="true"/>
                <property key="LOG_DELIVERING_EVENTS" value="true"/>
                <property key="LOG_SENDING_EVENTS" value="true"/>
                <property key="LOG_INTERNAL_EVENTS" value="true"/>
            </broker-plugin>
        </broker-plugins>
      </core>
    </configuration>

